=== hurynovich/ViolaJones4J/detector-opencv-impl/src/main/resources/cascade-classifier-schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:ocv="cascade-classifier"
        version="1.0"
        targetNamespace="cascade-classifier"
        elementFormDefault="qualified"
>
    <xs:element name="opencv_storage" type="ocv:root" />

    <xs:complexType name="root">
        <xs:annotation>
            <xs:documentation>
                Top level element.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence >
            <xs:element name="cascade" type="ocv:cascade" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="cascade">
        <xs:annotation>
            <xs:documentation>
                Contains object detection cascade.
            </xs:documentation>
        </xs:annotation>

        <xs:sequence>
            <xs:element name="stageType" type="xs:string" >
                <xs:annotation>
                    <xs:documentation>
                        Defines algorithm used for this cascade.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="featureType" type="ocv:featureType" />
            <xs:element name="height" type="xs:positiveInteger" />
            <xs:element name="width" type="xs:positiveInteger" />
            <xs:element name="stageParams" type="ocv:stageParams" />
            <xs:element name="featureParams" type="ocv:featureParams" />
            <xs:element name="stageNum" type="xs:positiveInteger" />
            <xs:element name="stages" type="ocv:stages" />
            <xs:element name="features" type="ocv:features" />
        </xs:sequence>
        <xs:attribute name="type_id" />
    </xs:complexType>

    <xs:complexType name="stageParams">
        <xs:sequence>
            <xs:element name="maxWeakCount" type="xs:positiveInteger" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="featureParams">
        <xs:sequence>
            <xs:element name="maxCatCount" type="xs:nonNegativeInteger" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stages">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="_" type="ocv:stage" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stage">
        <xs:sequence>
            <xs:element name="maxWeakCount" type="xs:positiveInteger" />
            <xs:element name="stageThreshold" />
            <xs:element name="weakClassifiers" type="ocv:weakClassifiers" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="weakClassifiers">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="_" type="ocv:weakClassifier" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="weakClassifier">
        <xs:sequence>
            <xs:element name="internalNodes" />
            <xs:element name="leafValues" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="features">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="_" type="ocv:feature" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="feature">
        <xs:sequence>
            <xs:element name="rects" type="ocv:rects" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="rects">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="_" type="ocv:rect" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="rect">
        <xs:annotation>
            <xs:documentation>
                <div xmlns="http://www.w3.org/1999/xhtml">
                    Holds data describing one rectangle within haar like feature. Its format is <strong>"x y w h f"</strong>.
                    <br/>
                    Where:
                    <br/>
                    <strong>x</strong>, <strong>y</strong> are base coordinates of the rectangle. They must be non negative integers since they reflect pixel position.
                    Coordinates are relative to detector window.
                    <br/>
                    <strong>w</strong>, <strong>h</strong> are width (size by X axis) and height (size by Y axis) of the rectangle. They must be non negative integers since they relative reflect pixel positions.
                    <br/>
                    <strong>f</strong> is decimal factor (multiplier) for integral value of pixels covered by this rectangle. It can be any decimal value.
                    <br/>
                    Example:
                    <br/>
                    <tt>2 3 5 10 -1.0</tt>
                </div>
            </xs:documentation>
        </xs:annotation>
        <xs:restriction>
            <!-- TODO -->
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="featureType">
        <xs:restriction>
            <xs:enumeration value="HAAR" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== hurynovich/ViolaJones4J/detector-opencv-impl/src/test/resources/haarcascade-sample.xml
<?xml version="1.0"?>
<opencv_storage
        xmlns="cascade-classifier"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="cascade-classifier cascade-classifier-schema.xsd"
>
    <cascade type_id="opencv-cascade-classifier">
        <stageType>BOOST</stageType>
        <featureType>HAAR</featureType>
        <height>20</height>
        <width>20</width>
        <stageParams>
            <maxWeakCount>93</maxWeakCount>
        </stageParams>
        <featureParams>
            <maxCatCount>0</maxCatCount>
        </featureParams>
        <stageNum>24</stageNum>
        <stages>
            <_>
                <maxWeakCount>6</maxWeakCount>
                <stageThreshold>-1.4562760591506958e+00</stageThreshold>
                <weakClassifiers>
                    <_>
                        <internalNodes>
                            0 -1 0 1.2963959574699402e-01
                        </internalNodes>
                        <leafValues>
                            -7.7304208278656006e-01 6.8350148200988770e-01
                        </leafValues>
                    </_>
                    <_>
                        <internalNodes>
                            0 -1 1 -4.6326808631420135e-02
                        </internalNodes>
                        <leafValues>
                            5.7352751493453979e-01 -4.9097689986228943e-01
                        </leafValues>
                    </_>
                </weakClassifiers>
            </_>
            <_>
                <maxWeakCount>12</maxWeakCount>
                <stageThreshold>-1.2550230026245117e+00</stageThreshold>
                <weakClassifiers>
                    <_>
                        <internalNodes>
                            0 -1 6 -2.1727620065212250e-01
                        </internalNodes>
                        <leafValues>
                            7.1098899841308594e-01 -5.9360730648040771e-01
                        </leafValues>
                    </_>
                    <_>
                        <internalNodes>
                            0 -1 7 1.2071969918906689e-02
                        </internalNodes>
                        <leafValues>
                            -2.8240481019020081e-01 5.9013551473617554e-01
                        </leafValues>
                    </_>
                </weakClassifiers>
            </_>
        </stages>
        <features>
            <_>
                <rects>
                    <_>
                        0 8 20 12 -1.
                    </_>
                    <_>
                        0 14 20 6 2.
                    </_>
                </rects>
            </_>
            <_>
                <rects>
                    <_>
                        9 1 4 15 -1.
                    </_>
                    <_>
                        9 6 4 5 3.
                    </_>
                </rects>
            </_>
        </features>
    </cascade>
</opencv_storage>
